name: mle1
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - ca-certificates=2021.5.30=ha878542_0
  - certifi=2021.5.30=py37h89c1867_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1k=h7f98852_0
  - pip=21.1.2=py37h06a4308_0
  - python=3.7.10=h12debd9_4
  - python_abi=3.7=1_cp37m
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py37h06a4308_0
  - spacy-model-en_core_web_sm=2.3.1=pyh9f0ad1d_0
  - sqlite=3.35.4=hdfb4753_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - adal==1.2.7
    - azure-common==1.1.27
    - azure-core==1.15.0
    - azure-graphrbac==0.61.1
    - azure-mgmt-authorization==0.61.0
    - azure-mgmt-containerregistry==8.0.0
    - azure-mgmt-core==1.2.2
    - azure-mgmt-keyvault==9.0.0
    - azure-mgmt-resource==13.0.0
    - azure-mgmt-storage==11.2.0
    - azureml-core==1.30.0
    - backports-tempfile==1.0
    - backports-weakref==1.0.post1
    - blis==0.4.1
    - catalogue==1.0.0
    - cffi==1.14.5
    - chardet==4.0.0
    - click==7.1.2
    - contextlib2==0.6.0.post1
    - cryptography==3.4.7
    - cymem==2.0.5
    - docker==4.4.4
    - idna==2.10
    - importlib-metadata==4.5.0
    - isodate==0.6.0
    - jeepney==0.6.0
    - jinja2==3.0.1
    - jmespath==0.10.0
    - joblib==1.0.1
    - jsonpickle==2.0.0
    - lightgbm==3.2.1
    - markupsafe==2.0.1
    - msrest==0.6.21
    - msrestazure==0.6.4
    - murmurhash==1.0.5
    - ndg-httpsclient==0.5.1
    - numpy==1.20.3
    - oauthlib==3.1.1
    - packaging==20.9
    - pandas==1.2.4
    - pathspec==0.8.1
    - pathy==0.5.2
    - plac==1.1.3
    - preshed==3.0.5
    - pyasn1==0.4.8
    - pycparser==2.20
    - pydantic==1.7.4
    - pyjwt==2.1.0
    - pyopenssl==20.0.1
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2021.1
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - ruamel-yaml==0.17.4
    - ruamel-yaml-clib==0.2.2
    - scikit-learn==0.24.2
    - scipy==1.6.3
    - secretstorage==3.3.1
    - six==1.16.0
    - sklearn==0.0
    - smart-open==3.0.0
    - spacy==2.3.0
    - spacy-legacy==3.0.6
    - srsly==1.0.5
    - thinc==7.4.1
    - threadpoolctl==2.1.0
    - tqdm==4.61.1
    - typer==0.3.2
    - typing-extensions==3.10.0.0
    - urllib3==1.26.5
    - wasabi==0.8.2
    - websocket-client==1.1.0
    - zipp==3.4.1
prefix: /home/kandy/anaconda3/envs/mle1

